"""rel_write - ROUND-TRIP WRITER for the RAGE audio `.rel` family (.rel + bare `datNNN`).

    original binary -> value model -> written back -> MUST reproduce the original bytes

WHY (maintainer ruling 2026-08-13): round-trip byte identity is the primary measure, and until
today this lane had a READER (`rel2xml.py`) that REFUSED 240 of 259 `.rel` and no writer at all -
which under that ruling makes the whole family **UNMEASURED, not passing**.

⭐⭐ SIZED FROM A VARIANT CENSUS, NOT FROM A REFUSAL MESSAGE (`tools/rel_census.py`,
2026-08-15). `rel2xml`'s refusal text and `docs/` both said "9 format families, 1 implemented";
the census says the same 9 IDENTS but shows what the refusal could not: **487 containers in the
corpus mirror (488 in the game), 621,223 item records, 330 layout variants**, and - the part that
matters - the CONTAINER IS ONE FORMAT ACROSS ALL NINE. What actually differs between the families
is the ITEM PAYLOAD SCHEMA, which is a different and much smaller claim than "nine formats".

MEASURED AT POPULATION (`tools/rel_population.py`, 2026-08-15, corpus mirror):
    487 / 487 byte-exact   mean 100.0000%   min 100.0000%   0 of 33,583,079 bytes unreached
    BYTE ACCOUNT: VALUE 20.92% | DERIVED 15.03% | ZERO-FILL 0.05% | CARRIED-VERBATIM 64.00%
    MUST-FAIL CONTROLS (`tools/rel_control.py`): 8 controls, worst catch rate 100.000%
⛔ QUOTE THE 64% WITH THE 100%. The item payload is copied, not understood.

================================  WHAT IS MODELLED  ================================
Everything except the inside of an item's payload. Concretely, on write:

  COMPUTED (not carried - a wrong model MOVES these and the round-trip rejects it):
    * DataLength           = the end of the laid-out data block
    * every item's DATA OFFSET, by the layout law below
    * every item's index LENGTH  = 4 + len(payload)
    * ItemCount, NameTableCount, NameTableLength, ListACount, ListBCount
    * every name-table string OFFSET, from the decoded string list
  VALUE (re-encoded from a decoded value, never memcpy'd):
    * RelIdent, Version
    * per item: the {u8 type | u24 ntOffset} word, split and recomposed
    * per item: the index NameHash (or, in the named-index variant, the name STRING)
    * the name-table strings themselves, and every ListA/ListB entry
  CARRIED VERBATIM (declared, and reported by `regions()` in bytes):
    * the item PAYLOAD - record bytes past the 4-byte header.

⛔ THE LAW THIS VAULT LEARNED THE HARD WAY: a claimed region is evidence ONLY IF A WRONG CLAIM
COULD HAVE BEEN REJECTED. So `regions()` is not decoration - QUOTE IT WITH THE COVERAGE FIGURE.
The payload is 63.9% of this family by byte and it is COPIED, not understood. What the round-trip
does prove is that the CONTAINER and the LAYOUT are rebuilt from values, because the offsets and
lengths that place those payloads are recomputed: shift one record by one byte and every later
offset, the DataLength and the index all move.

===========================  THE LAYOUT LAW (derived 2026-08-15)  ===========================
An item's data offset is NOT stored information a writer must copy. Items are laid out in
ascending-offset order starting at data offset 4 (0..3 is the version stamp), and

        off = align(previous_record_end, A)      A = A(ident, item type)

A is a property OF THE RECORD TYPE. Found by `tools/rel_align_derive.py`: `dat15` leaves 1/2/3
byte gaps and in every one of them the NEXT record is type 0 and the gap lands the cursor on a
multiple of 4; `dat151` leaves 4/8/12-byte gaps from an already-4-aligned cursor when the next
record is type 37 or 38 - i.e. 16-byte alignment.

MEASURED AT POPULATION 2026-08-15, over all 487 containers and all 621,223 item records:
    330 of 330 (ident, index-encoding, type) variants take ONE consistent A
        A=1 x298   A=2 x1   A=4 x25   A=8 x1   A=16 x5
    621,223 / 621,223 records explained          = 100.0000%
    487 / 487 containers rebuild their WHOLE offset vector AND DataLength from the law
The table lives in `rel_layout.json` and is regenerated by `tools/rel_align_derive.py`.
⛔ A variant with no entry in that table falls back to the DECODED offset and the file is counted
`layout_carried` - never silently, `regions()` reports it. That counter reads 0 / 487 today.

=========================  TWO ITEM-INDEX ENCODINGS, NOT ONE  =========================
The item index is normally `{u32 NameHash, u32 Offset, u32 Length}[ItemCount]`. The two
`audioconfig.dat4.rel` files (base + update) instead carry
`{u8 nameLen, char[nameLen] name, u32 Offset, u32 Length}[ItemCount]` - a STRING-NAMED index.
Those two were the family's only "malformed" containers under a hash-index-only reader (they
read a ListA count of 0x54525453). They are not malformed; they are a second encoding, and the
discriminator is not the filename - it is which encoding CONSUMES THE FILE EXACTLY. With it the
container parses 487/487.

=====================  THE ntOffset FIELD IS PINNED, NOT ASSUMED  =====================
Splitting a dword into u8|u24 and re-packing it always reproduces the dword, so byte identity
alone cannot pin that split. It is pinned INDEPENDENTLY, by `tools/rel_nametable_link.py`: read
the u24 as a byte offset into the sibling `X.datNNN.nametable`, take the NUL-terminated string
there, joaat it lowercased, and compare with the item's own index NameHash. Over the population
that resolves **91,355 / 91,355 items = 100.000%** for dat10/dat15/dat54/dat149/dat150/dat151,
while the same offsets read against the container's INLINE name table match 0 / 133,646. It is
REFUTED for `dat4` (532 / 42,291 = 1.258%), whose records are 1-8 bytes long and cannot hold a
4-byte header at all - so this writer does not claim a header split for `dat4`.

ASCII output only.
"""
import json
import os
import struct
import sys as _sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_sys.path.insert(0, _HERE)

# ident -> True when {u8 type | u24 ntOffset} is PINNED for that family (see the module note).
# dat4 is REFUTED (1.258%); dat16/dat22 ship no sidecar so the split is UNTESTED there and this
# writer does not claim it. An unclaimed header is simply part of the payload - carried, and
# counted as carried, which is the honest failure.
HEADER_PINNED = {10: True, 15: True, 54: True, 149: True, 150: True, 151: True,
                 4: False, 16: False, 22: False}


def _load_layout():
    p = os.path.join(_HERE, 'rel_layout.json')
    if not os.path.isfile(p):
        return {}
    with open(p, encoding='utf-8') as f:
        return json.load(f).get('align', {})


ALIGN = _load_layout()


class RelWriteError(Exception):
    """Outside the measured container envelope. Refuse loudly; never half-read."""


def _align(x, a):
    return ((x + a - 1) // a) * a


def _parse_index_hash(b, p, n):
    """{u32 hash, u32 off, u32 len}[n] -> (entries, cursor). Raises on overrun."""
    if p + 12 * n > len(b):
        raise RelWriteError('hash index (%d entries) overruns the file' % n)
    ents = [struct.unpack_from('<III', b, p + 12 * i) for i in range(n)]
    return ents, p + 12 * n


def _parse_index_named(b, p, n):
    """u32 NameBytes, then {u8 len, char[len] name, u32 off, u32 len}[n] -> (entries, cursor).

    NameBytes == sum(1 + len(name)) over the entries - i.e. the table's byte size MINUS the
    fixed 8 bytes per entry. Measured on both files that use this encoding: 2,524 for 129
    entries (3,556 - 129*8) and 2,720 for 136 (3,808 - 136*8). It is therefore COMPUTED on
    write, never carried.
    """
    if p + 4 > len(b):
        raise RelWriteError('named index name-bytes word missing')
    want = struct.unpack_from('<I', b, p)[0]
    p += 4
    start = p
    ents = []
    for _ in range(n):
        if p >= len(b):
            raise RelWriteError('named index overruns the file')
        ln = b[p]
        if ln == 0 or p + 1 + ln + 8 > len(b):
            raise RelWriteError('named index entry is not a length-prefixed name')
        nm = b[p + 1:p + 1 + ln]
        if not all(32 <= c < 127 for c in nm):
            raise RelWriteError('named index entry is not printable ASCII')
        off, l2 = struct.unpack_from('<II', b, p + 1 + ln)
        ents.append((nm, off, l2))
        p += 1 + ln + 8
    got = (p - start) - 8 * n
    if got != want:
        raise RelWriteError('named index NameBytes word says %d, the names measure %d'
                            % (want, got))
    return ents, p


def _parse_lists(b, p):
    if p + 4 > len(b):
        raise RelWriteError('trailing list A missing')
    na = struct.unpack_from('<I', b, p)[0]
    p += 4
    if p + 4 * na > len(b):
        raise RelWriteError('trailing list A (%d) overruns the file' % na)
    la = list(struct.unpack_from('<%dI' % na, b, p)) if na else []
    p += 4 * na
    if p + 4 > len(b):
        raise RelWriteError('trailing list B missing')
    nb = struct.unpack_from('<I', b, p)[0]
    p += 4
    if p + 4 * nb > len(b):
        raise RelWriteError('trailing list B (%d) overruns the file' % nb)
    lb = list(struct.unpack_from('<%dI' % nb, b, p)) if nb else []
    p += 4 * nb
    return la, lb, p


class Rel(object):
    """The value model. Nothing here is a byte range except an item's payload."""

    def __init__(self, blob):
        b = bytes(blob)
        self.orig = b
        self.size = len(b)
        if self.size < 20:
            raise RelWriteError('.rel shorter than a header (%d B)' % self.size)
        self.ident = struct.unpack_from('<I', b, 0)[0]
        dl = struct.unpack_from('<I', b, 4)[0]
        if 8 + dl > self.size:
            raise RelWriteError('DataLength %d overruns the file (%d B)' % (dl, self.size))
        self.datalen_src = dl
        self.version = struct.unpack_from('<I', b, 8)[0] if dl >= 4 else 0

        p = 8 + dl
        ntlen = struct.unpack_from('<I', b, p)[0]
        ntbase = p + 4
        if ntlen < 4 or ntbase + ntlen > self.size:
            raise RelWriteError('name table (len %d @%d) overruns the file' % (ntlen, ntbase))
        ntc = struct.unpack_from('<I', b, ntbase)[0]
        if ntbase + 4 + 4 * ntc > self.size:
            raise RelWriteError('name table offset array (%d) overruns the file' % ntc)
        offs = [struct.unpack_from('<I', b, ntbase + 4 + 4 * i)[0] for i in range(ntc)]
        nblob = b[ntbase + 4 + 4 * ntc: ntbase + ntlen]
        # DECODE to strings. A hole, an overlap or a re-ordering makes the rebuild differ.
        self.nt_strings = []
        for o in offs:
            if not (0 <= o < len(nblob)):
                raise RelWriteError('name-table offset %d outside the %d B blob' % (o, len(nblob)))
            e = nblob.find(b'\x00', o)
            if e < 0:
                raise RelWriteError('name-table string at %d is not NUL-terminated' % o)
            self.nt_strings.append(nblob[o:e])

        p = ntbase + ntlen
        if p + 4 > self.size:
            raise RelWriteError('item count missing')
        n = struct.unpack_from('<I', b, p)[0]
        p += 4
        # TWO ENCODINGS. The discriminator is which one consumes the file EXACTLY.
        self.index_kind = None
        for kind, fn in (('hash', _parse_index_hash), ('named', _parse_index_named)):
            try:
                ents, q = fn(b, p, n)
                la, lb, end = _parse_lists(b, q)
            except (RelWriteError, struct.error):
                continue
            if end == self.size:
                self.index_kind = kind
                self.entries, self.lista, self.listb = ents, la, lb
                break
        if self.index_kind is None:
            raise RelWriteError('neither the hash index nor the named index consumes the file '
                                'exactly (ident %d, %d items)' % (self.ident, n))

        # ---- decode every item to {key, type, ntoff, payload}
        pinned = HEADER_PINNED.get(self.ident, False)
        self.items = []
        for key, off, ln in self.entries:
            a = 8 + off
            if a + ln > self.size or ln < 0:
                raise RelWriteError('item (off %d len %d) outside the file' % (off, ln))
            rec = b[a:a + ln]
            if pinned and ln >= 4:
                w = struct.unpack_from('<I', rec, 0)[0]
                self.items.append({'key': key, 'src_off': off, 'type': w & 0xFF,
                                   'ntoff': w >> 8, 'payload': rec[4:]})
            else:
                self.items.append({'key': key, 'src_off': off, 'type': None,
                                   'ntoff': None, 'payload': rec})
        # LAYOUT ORDER: ascending source offset. The permutation is part of the model.
        self.order = sorted(range(len(self.items)), key=lambda i: self.items[i]['src_off'])
        self.layout_derived = None      # set by _layout()
        self._layout()

    # ------------------------------------------------------------------ layout
    def _rec_len(self, it):
        return (4 + len(it['payload'])) if it['type'] is not None else len(it['payload'])

    def _type_key(self, it):
        """The alignment law is keyed by the record's TYPE - and ONLY where a type is CLAIMED.

        ⛔ Δ 2026-08-15: the first cut keyed un-headered records by `payload[0]`, i.e. by a byte
        it had just declined to interpret. That invented 216 pseudo-variants for `dat4` and left
        one of them ("type 5", 28 records in 4 files) with no consistent alignment - a hole
        manufactured entirely by the keying. A family whose header split this writer does not
        claim gets ONE alignment bucket (-1), which is what "we do not know the type" means.
        """
        return it['type'] if it['type'] is not None else -1

    def align_key(self, it):
        """The alignment table's key: (RelIdent, INDEX ENCODING, item type).

        ⭐ THE INDEX ENCODING IS PART OF THE VARIANT, and leaving it out cost a whole family.
        `dat4` is 68 hash-index containers whose records are laid out strictly packed (A=1) plus
        2 `audioconfig.dat4.rel` string-named-index containers that are laid out differently.
        Keyed on ident alone those 2 files make all 264,970 `dat4` records "unexplained"; keyed
        with the encoding, each variant takes one consistent A. The encoding is not a guess - it
        is the discriminator that CONSUMES THE FILE EXACTLY, decided in __init__.
        """
        if self.index_kind == 'named':
            # ⭐ IN THE NAMED-INDEX ENCODING THE NAME *IS* THE TYPE. These containers carry no
            # type byte, and their records are config slots addressed by name
            # (DRIVERSETTINGS_WAVEROOTPATH, ENGINESETTINGS_ORIENTATION...). Keyed by name the
            # layout resolves completely: 264 of the 265 records are strictly packed and exactly
            # one - ENGINESETTINGS_ORIENTATION_SMOOTH_RATE - is 16-aligned, identically in both
            # files.
            # ⚠ DENOMINATOR, STATED: this sub-table has only TWO observations per key, because
            # only two files in the game use this encoding (base + update copies of
            # audioconfig.dat4.rel). Two agreeing witnesses is thin evidence and is reported as
            # thin, not laundered into the family-wide figure.
            return '%d:named:%s' % (self.ident, it['key'].decode('latin-1'))
        return '%d:%s:%d' % (self.ident, self.index_kind, self._type_key(it))

    def _layout(self):
        """COMPUTE every item's data offset. Sets self.offsets (index-order) and
        self.layout_derived (True when every offset came from the law, False when at least one
        fell back to the decoded value - which is CARRIED and reported)."""
        self.offsets = [0] * len(self.items)
        derived = True
        prev = 4
        for i in self.order:
            it = self.items[i]
            a = ALIGN.get(self.align_key(it))
            if a is None:
                self.offsets[i] = it['src_off']
                derived = False
                prev = it['src_off'] + self._rec_len(it)
                continue
            o = _align(prev, a)
            self.offsets[i] = o
            prev = o + self._rec_len(it)
        self.datalen = prev
        self.layout_derived = derived

    # ------------------------------------------------------------------ write
    def write(self):
        img = bytearray(self.size)                      # ZERO-FILLED: gaps stay LOUD
        struct.pack_into('<II', img, 0, self.ident, self.datalen)
        if self.datalen >= 4 and 12 <= self.size:
            struct.pack_into('<I', img, 8, self.version)
        # ---- data block, per RECORD (never one slab)
        for i, it in enumerate(self.items):
            o = 8 + self.offsets[i]
            if it['type'] is not None:
                if o + 4 > self.size:
                    continue
                struct.pack_into('<I', img, o, (it['type'] & 0xFF) | ((it['ntoff'] & 0xFFFFFF) << 8))
                o += 4
            pl = it['payload']
            if o + len(pl) <= self.size:
                img[o:o + len(pl)] = pl
        # ---- name table: LENGTH, COUNT and every OFFSET are COMPUTED from the string list
        p = 8 + self.datalen
        blob = b''.join(s + b'\x00' for s in self.nt_strings)
        offs, at = [], 0
        for s in self.nt_strings:
            offs.append(at)
            at += len(s) + 1
        ntlen = 4 + 4 * len(self.nt_strings) + len(blob)
        if p + 4 <= self.size:
            struct.pack_into('<I', img, p, ntlen)
        p += 4
        if p + 4 <= self.size:
            struct.pack_into('<I', img, p, len(self.nt_strings))
        for k, o in enumerate(offs):
            q = p + 4 + 4 * k
            if q + 4 <= self.size:
                struct.pack_into('<I', img, q, o)
        q = p + 4 + 4 * len(offs)
        if q + len(blob) <= self.size:
            img[q:q + len(blob)] = blob
        p += ntlen
        # ---- item index: COUNT computed, OFFSET computed, LENGTH computed
        if p + 4 <= self.size:
            struct.pack_into('<I', img, p, len(self.items))
        p += 4
        for i, it in enumerate(self.items):
            ln = self._rec_len(it)
            if self.index_kind == 'hash':
                if p + 12 <= self.size:
                    struct.pack_into('<III', img, p, it['key'], self.offsets[i], ln)
                p += 12
            else:
                if i == 0:
                    # NameBytes - COMPUTED from the decoded names, never carried.
                    nb = sum(1 + len(x['key']) for x in self.items)
                    if p + 4 <= self.size:
                        struct.pack_into('<I', img, p, nb)
                    p += 4
                nm = it['key']
                if p + 1 + len(nm) + 8 <= self.size:
                    img[p] = len(nm)
                    img[p + 1:p + 1 + len(nm)] = nm
                    struct.pack_into('<II', img, p + 1 + len(nm), self.offsets[i], ln)
                p += 1 + len(nm) + 8
        # ---- trailing lists: COUNTS computed from the decoded lists
        for lst in (self.lista, self.listb):
            if p + 4 <= self.size:
                struct.pack_into('<I', img, p, len(lst))
            p += 4
            for v in lst:
                if p + 4 <= self.size:
                    struct.pack_into('<I', img, p, v)
                p += 4
        self.written_end = p
        return bytes(img)

    # ------------------------------------------------------------------ measure
    def unreached(self):
        """(count, non_zero_count) of bytes the model never reproduced.

        A ZERO gap is padding we did not have to understand; a NON-ZERO gap is data we are
        dropping - which is exactly what this exercise exists to surface."""
        got, orig = self.write(), self.orig
        n = min(len(got), len(orig))
        bad = [i for i in range(n) if got[i] != orig[i]]
        return len(bad), sum(1 for i in bad if orig[i] != 0)

    def regions(self):
        """Byte account of the IMAGE: (value, derived, zero_fill, carried).

        ⭐ DISCLOSURE, NOT DECORATION - this vault's law is that a claimed region is evidence
        ONLY IF A WRONG CLAIM COULD HAVE BEEN REJECTED, and byte identity cannot tell a rebuilt
        region from a copied one. `carried` is the part of a passing file that could not have
        failed. Quote it NEXT TO the coverage figure, never instead of it.
        """
        nitems = len(self.items)
        hdr_items = sum(1 for it in self.items if it['type'] is not None)
        payload = sum(len(it['payload']) for it in self.items)
        blob = sum(len(s) + 1 for s in self.nt_strings)
        # DERIVED: DataLength, NameTableLength, NameTableCount, nt offsets, ItemCount,
        # per-item index offset+length words, ListA/ListB counts.
        derived = 4 + 4 + 4 + 4 * len(self.nt_strings) + 4 + 8 * nitems + 8
        if self.index_kind == 'named' and nitems:
            derived += 4                 # the COMPUTED NameBytes word
        if not self.layout_derived:
            derived -= 4 * nitems        # the offset words were CARRIED for this file
        # VALUE: ident, version, the item header words, index keys, nt strings, list values
        keybytes = (4 * nitems if self.index_kind == 'hash'
                    else sum(1 + len(it['key']) for it in self.items))
        value = 4 + 4 + 4 * hdr_items + keybytes + blob + 4 * (len(self.lista) + len(self.listb))
        if not self.layout_derived:
            value += 4 * nitems
        carried = payload
        zero = self.size - value - derived - carried
        return value, derived, zero, carried


def read_rel(src):
    blob = bytes(src) if isinstance(src, (bytes, bytearray)) else open(src, 'rb').read()
    return Rel(blob)
